### ISSUE TITLE
Mimic Palette Class from Android

### ISSUE THREAD

**Issue by aleufms** [ViccAlexander/Chameleon#100]
It would be cool if Chamelon got support to extract the Vibrant and Muted colors from an image.

Class in Android: https://developer.android.com/reference/android/support/v7/graphics/Palette.html
A JS implementation: https://jariz.github.io/vibrant.js/

**Comment by bre7** [comment]
Try one of these libs: https://github.com/search?l=Swift&q=android+Palette&ref=searchresults&type=Repositories&utf8=%E2%9C%93
