### ISSUE TITLE
Impact of global theme setting

### ISSUE THREAD

**Issue by sumowesley** [ViccAlexander/Chameleon#102]
Hi there.

I have set a global theme by a colour stored in my settings singleton using the following:

```objc
[Chameleon setGlobalThemeUsingPrimaryColor:settings.colourScheme withContentStyle:UIContentStyleContrast];
```
This is Xcode 7.2.1 and a target of IOS 9.2.

The scheme colour is from a choice of the darker colours that form part of the Chameleon flat colours.

The theme gives some much needed punch to the navigationControllers in particular. There seem to be a few side effects to applying the theme (e.g. #98) and a few others. An example is the use of the 'SFSafariViewController' which is presented (not pushed) from a 'UINavigationController' embedded view controller and has an odd combination of colours when it appears

The following is how the top bar of the 'SFSafariViewController' appears if I set the global tint colour of the app's window in the AppDelegate:
![image](https://cloud.githubusercontent.com/assets/5694619/13022540/2a6c92ca-d1da-11e5-8c8a-e9886fc5aac3.png)

If I have set a global theme colour using Chameleon in the same AppDelegate I get the following when I present that same `SFSafariViewController`:
![image](https://cloud.githubusercontent.com/assets/5694619/13022563/4a842d84-d1da-11e5-942c-32fc372fc2f3.png)

Are there any suggestion on how I get get the errant top section to behave once I have set a theme?

**Comment by bre7** [comment]
Impact of Chameleon on SFSafariViewController was previously reported in https://github.com/ViccAlexander/Chameleon/issues/74. The last comment has a workaround, as stated in the README, Themes are still in beta.

**Comment by sumowesley** [comment]
Good of you to let me know. I appreciate that themes are in beta but the fix will ease my eyes while I test my app.
