### ISSUE TITLE
How to change color of the status bar?

### ISSUE THREAD

**Issue by MariamNers** [ViccAlexander/Chameleon#109]
I have tried a couple of things before asking this question on here, but nothing worked. So since I am using your framework, does anyone know how I can change the color of the status bar? 

![screen shot 2016-03-13 at 22 06 48](https://cloud.githubusercontent.com/assets/17073482/13739871/892061ea-e9c5-11e5-9b16-0da2ef1af56c.png)

**Comment by bre7** [comment]
Do you want to change the style or the "background color" ? Style change allows you to set the text to either black or white. If you want to add a background color you need to create a view

**Comment by MariamNers** [comment]
Thank you, fixed it
