### ISSUE TITLE
'appearanceWhenContainedIn:' is deprecated: first deprecated in iOS 9.0 

### ISSUE THREAD

**Issue by MariamNers** [ViccAlexander/Chameleon#110]
Out of nowhere I am getting this warning when I run my project. I have changed absolutely nothing and the framework was working perfectly for me before this happened. 

The warning is this:  ` 'appearanceWhenContainedIn:' is deprecated: first deprecated in iOS 9.0 - Use +appearanceWhenContainedInInstancesOfClasses: instead` 

This causes my simulator to move ridiculously slow from one controller to another controller and its impossible to work with. I have tried rebooting Xcode and simulator but still no luck. Did anyone else have this issue? 
![screen shot 2016-03-19 at 23 11 18](https://cloud.githubusercontent.com/assets/17073482/13901825/ab872450-ee28-11e5-91f5-656d73f1d12e.png)

**Comment by bre7** [comment]
Suggestion: Use the new API and check whether it does fix the problem or not. As the readme states, themes are still in beta

**Comment by MariamNers** [comment]
You mean the Chameleon API? If yes, then I use the latest version of it on github. But now I have got another error `Target 'Pods' of project 'Pods' was rejected as an implicit dependency for 'Pods.framework' because its architectures 'i386' didn't contain all required architectures 'i386 x86_64'` that stops my project from running. I have got only Chameleon Framework in my pod file. It then says `No such module 'ChameleonFramework'` and I can't get it to work at all. I tried cleaning and then building, deleting derived data, updating pod files, but nothing.

**Comment by ViccAlexander** [comment]
Chameleon currently is using the recently deprecated methods. However the Objective-C version silences these warnings. It could be that the swift version does not (@bre7 confirmation?). Also for the second error make sure you have the following line at the beginning of your pod file `use_frameworks!` and check [this](https://github.com/CocoaPods/CocoaPods/issues/2053) out.

Sorry for getting back to you really late. :disappointed: 

Thanks for using Chameleon!

**Comment by bre7** [comment]
True, `appearanceWhenContainedInInstancesOfClasses` is deprecated.
