### ISSUE TITLE
Radial gradients

### ISSUE THREAD

**Issue by stephenkopylov** [ViccAlexander/Chameleon#111]
Hi!
In "UIColor+Chameleon.m", in method
`+ (UIColor *)colorWithGradientStyle:(UIGradientStyle)gradientStyle withFrame:(CGRect)frame andColors:(NSArray *)colors;`
in line
`float myRadius = MIN(frame.size.width, frame.size.height) * 1.0;`
maybe you means diameter? because radius must be a half of side, so, as I think code with "* 0.5" shows better results. Meantime now radial gradients look little bit wrong.
What do you think?

**Comment by stephenkopylov** [comment]
Pull request created https://github.com/ViccAlexander/Chameleon/pull/112

**Comment by ViccAlexander** [comment]
Thanks @stephenkopylov will verify just to make sure. If everything is well, I'll accept it. Cheers!

**Comment by stephenkopylov** [comment]
Hi, man!
What about this bug?
