### ISSUE TITLE
Swift and setGlobalThemeUsingPrimaryColor

### ISSUE THREAD

**Issue by DavidGagne** [ViccAlexander/Chameleon#115]
Is there a way to implement the setGlobalThemeUsingPrimaryColor feature in Swift or is that only available in Obj-C?

**Comment by bre7** [comment]
You can use objc code in swift.

E.g:
```swift
Chameleon.setGlobalThemeUsingPrimaryColor(FlatPlum(), withContentStyle: .Light)
```

**Comment by DavidGagne** [comment]
Oh, awesome. And ... Would you drop that into the AppDelegate didFinishLaunchingWithOptions? How can you set it to apply to the entire app?

**Comment by bre7** [comment]
Yeah, you can use the method in `didFinishLaunchingWithOptions`

**Comment by DavidGagne** [comment]
Using FlatPlum() doesn't work, but when I tried with UIColor.flatSandColor() it does compile.
Thanks!

**Comment by bre7** [comment]
Follow the Installation instructions, FlatPlum() is a shorthand method located in the swift file.

**Comment by DavidGagne** [comment]
Ah. I used pod 'ChameleonFramework' instead of pod 'ChameleonFramework/Swift'.

Now the shorthand methods are working.

**Comment by bre7** [comment]
:wink:

**Comment by Dharin-shah** [comment]
Hey @bre7  I cant seem to call **setGlobalThemeUsingPrimaryColor** using the viewcontroller's instance (self) in swift.

**Comment by bre7** [comment]
Hi, just to be sure: have you followed the installation instructions ? Are you able to call `FlatPlum()` for instance ?

**Comment by Dharin-shah** [comment]
Yup, i have been using flat colors for months, i decided to use the theme feature and got this, Although i can set the theme globally however since i have a tab navigation to other view controllers this messes up my ui

**Comment by bre7** [comment]
https://github.com/ViccAlexander/Chameleon#theme-methods

`setGlobalThemeUsingPrimaryColor` is a static method on Chameleon.
`setThemeUsingPrimaryColor` is an instance method of UIViewController.

**Comment by Dharin-shah** [comment]
Oops oops, I am really sorry for my ignorance, that was stupid. Thank You. Just another question, how do I set the font name but its attribute (i.e bold ,italic) could be inferred from the IB

**Comment by bre7** [comment]
What do you mean ?
