### ISSUE TITLE
Colors from Image got repeat color

### ISSUE THREAD

**Issue by luiyezheng** [ViccAlexander/Chameleon#117]
I found If I generate flat colors from image, sometimes I would get repeat colors. 

For example:
<img width="175" alt="2016-06-05 11 32 26" src="https://cloud.githubusercontent.com/assets/10849914/15806435/dd7f4386-2b75-11e6-945c-5ae1e9a10f32.png">

I used ` NSArray(ofColorsFromImage: self.imageView.image, withFlatScheme: true)` to generate the colors. Is this a normal behavior? Or Did I do something wrong? Thanks.:-)

**Comment by seieibob** [comment]
I'd venture a guess that you'd have to set `withFlatScheme` to `false`. What you're using grabs the most common colors, and I'd venture that most of them are greenish in your sample image. There aren't that many shades of green in the flat color set, so when they're matched to the nearest flat color you'll get duplicates.

From the readme:
> Due to the limited number of flat colors currently available, color schemes may return results that reuse certain flat colors. Because of this redundancy, we have provided an option to return either a flat color scheme or a non-flat color scheme until more flat colors are added to the inventory.

**Comment by ViccAlexander** [comment]
Thanks for stepping in @seieibob. Perfect answer.
