### ISSUE TITLE
Error when apply gradient color to view backgroundColor

### ISSUE THREAD

**Issue by bayarmanlai** [ViccAlexander/Chameleon#122]
```swift
view.backgroundColor = UIColor(gradientStyle: UIGradientStyle.LeftToRight, withFrame: self.frame, andColors: [UIColor(hexString: "3589ae"), UIColor(hexString: "33b0ac")])
```

> **Error**
> <Error>: CGContextSaveGState: invalid context 0x0. If you want to see the backtrace, please set CG_CONTEXT_SHOW_BACKTRACE environmental variable.

**Comment by bre7** [comment]
Try unwrapping the UIColors.  Nullability annontations are missing, but `UIColor(hexString:)` should return `UIColor?`
