### ISSUE TITLE
How do i do the theme in one line in swift?

### ISSUE THREAD

**Issue by arashdoescode** [ViccAlexander/Chameleon#129]
Im confused regarding the content style in the theme, how would i get the content style?

**Comment by bre7** [comment]
Not sure what you mean. Are you asking how to use the Theme methods ? Docs: https://github.com/ViccAlexander/Chameleon#theme-methods

E.g:
```swift
Chameleon.setGlobalThemeUsingPrimaryColor(FlatMint(), withContentStyle:.Contrast)
```
