### ISSUE TITLE
Using ARGB hex code causes crash. 

### ISSUE THREAD

**Issue by levibostian** [ViccAlexander/Chameleon#132]
Chameleon v2.1.0 Swift implementation. 

Creating a UIColor in my app via HexColor. I am however, not using RGB but ARGB:

```swift
static let primaryColor: UIColor = HexColor("#FF216085")
```

When I go to access primaryColor, exception thrown in my app in ChameleonShorthand.swift lines 81 - 83:

```swift
public func HexColor(hexString: String, _ alpha: CGFloat = 1.0) -> UIColor {
    return UIColor(hexString: hexString, withAlpha: alpha)
}
```

When I remove "FF" to become a RGB code, no exception. 

---

Unfortunately, this is the full stacktrace that I have. I am not sure how to get you any more information. Would be happy to help if I can.

**Comment by bre7** [comment]
Hi @levibostian , 

`HexColor(,_)` is supposed to take 2 arguments: hexcode of a color (RGB only), and then the alpha as a 2nd argument. Poor documentation in this case and lack of parameter checking caused an exception.

**Comment by levibostian** [comment]
That is what I figured. Added as an issue to add some error handling around it. 

Thanks!

**Comment by ViccAlexander** [comment]
Thanks for sharing @levibostian. Will add it to the TODO list.

**Comment by bre7** [comment]
Fix: UIColor(hexString...) should return `nullable UIColor*`
