### ISSUE TITLE
[Feature/Update] Update to Swift v3 Compliance

### ISSUE THREAD

**Issue by mathmatrix828** [ViccAlexander/Chameleon#137]
Swift 3 changes the name convention to lowerCamelCase
```swift
let color: UIColor = .white
```
Updating Chameleon to this convention, in addition to making them members of a class instead of a function, with put this framework into compliance.
```swift
let color: UIColor = .flatWhite
```

Awesome job overall though! I love this framework!

**Comment by bre7** [comment]
PRs are welcome :wink: I don't have the time to apply the swift 3 guidelines and neither does Vic (probably)

**Comment by AlexMcArdle** [comment]
#135 fixes this. Please merge.

**Comment by bre7** [comment]
👍 Shorthand methods (some at least) aren't necessary imo (e.g: `FlatPurple()` ~> `UIColor.flatPurple` or just `.flatPurple`)

cc @ViccAlexander

**Comment by mathmatrix828** [comment]
@AlexMcArdle your PR doesn't address the issue I brought up

**Comment by bre7** [comment]
You are welcome to change class functions in objc to stored variables

**Comment by ViccAlexander** [comment]
Haven't had time to dwell into Swift, so giving you full reign over anything Swift @bre7 😃

**Comment by bre7** [comment]
👍 If no one submits a PR, I'll try to get on it as soon as I can

**Comment by ViccAlexander** [comment]
Leaving this issue open even though #135 was merged. That way we can try to get the changes @mathmatrix828 suggested into Chameleon.

**Comment by ViccAlexander** [comment]
@mathmatrix828 Check out the app-extension branch's [ChameleonShorthand.swift](https://github.com/ViccAlexander/Chameleon/blob/app-extension/Pod/Classes/Swift/ChameleonShorthand.swift) file. I've gone ahead and removed several shorthand files to conform to the new Swift 3 standards. You can now call methods using `.flatPurple()`. Also what did you mean by making them members of a class instead of functions?

**Comment by bre7** [comment]
Colors are now variables though. So it should be `.flatPurple`

**Comment by mathmatrix828** [comment]
Exactly

**Comment by mathmatrix828** [comment]
Looks like the updated files are Swift-3 compliant, great job guys!

**Comment by jspenc72** [comment]
Any update on Swift 3 compatibility @bre7 ?

**Comment by bre7** [comment]
Check #142. Branch will be merged after the conflicts are resolved.

**Comment by bre7** [comment]
Merged.
