### ISSUE TITLE
Update pods to 2.2?

### ISSUE THREAD

**Issue by rajatk** [ViccAlexander/Chameleon#149]
not able to get `ChameleonFramework/Swift (~> 2.2.0)` through Cocoapods. Is a new release or pod change coming soon?

**Comment by bre7** [comment]
https://github.com/ViccAlexander/Chameleon/releases 2.2 was just a tag. Try again or use master

**Comment by rajatk** [comment]
still no luck with Pod, it can't find that release.

Meanwhile, i'll use master. Was on swift3 branch which is now behind so master should work.
