### ISSUE TITLE
Is there a timeline for merging swift 3 branch into master branch?

### ISSUE THREAD

**Issue by wx0165927473** [ViccAlexander/Chameleon#150]
Thanks

**Comment by bre7** [comment]
Hi Xin,

Did you check the project first ? It's already swift3 compatible. The swift3 branch is just an old branch.

**Comment by wx0165927473** [comment]
I installed by using cocoapods. When I compile and build the project, it still remind me to covert to Swift 3. BTW I used master branch. Here is the pod file:
use_frameworks!
target “GameTracker” do
     pod 'ChameleonFramework/Swift'
end

Any suggestions? Thanks

**Comment by bre7** [comment]
You aren't using master in that Podfile

**Comment by allenlinli** [comment]
Excuse me, how to use master in that podfile?
Shouldn't it be the master by default?

**Comment by allenlinli** [comment]
I figured out I need to update cocoapod repo or cocoapod. Problem solved, thanks.

**Comment by allenlinli** [comment]
Cocoapod only got 2.1.0 as its newest one, would you like to update it?

**Comment by bre7** [comment]
```ruby
pod 'ChameleonFramework/Swift', :git => 'https://github.com/ViccAlexander/Chameleon.git'
