### ISSUE TITLE
Crash App when push view

### ISSUE THREAD

**Issue by mengheangrat** [ViccAlexander/Chameleon#152]
>Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Only RGBA or White color spaces are supported in this situation.'

**Comment by bre7** [comment]
Could you provide context to the crash ? Sample code ?

**Comment by mengheangrat** [comment]
Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Only RGBA or White color spaces are supported in this situation.'

**Comment by mengheangrat** [comment]
navigationBarAppearace.barTintColor = GradientColor(.topToBottom, frame: CGRect(x: 0, y: 0, width: 100, height: 100), colors: [UIColor.red,UIColor.lightGray, UIColor.blue]);

**Comment by bre7** [comment]
Not sure what you are sharing. Line that caused the crash ? Where is it located ?
Works without any problems on the sample project. Provide a demo project or we won't be able to help out.
