### ISSUE TITLE
Controlling UIWebView video player button appearance

### ISSUE THREAD

**Issue by inzinga** [ViccAlexander/Chameleon#154]
Within my App, I set a global theme using:

``` objc
[Chameleon setGlobalThemeUsingPrimaryColor:primaryColor withSecondaryColor:secondaryColor andContentStyle:UIContentStyleContrast];
```

Then, clean up the appearance of several UIButton's using:

``` objc
[[UIButton appearanceWhenContainedInInstancesOfClasses:@[[AVPlayerViewController class]]] setBackgroundColor:[UIColor clearColor]];
```

However, when playing any video inside a UIWebView, I'm unable to modify the global theme applied to buttons within the UIWebView-based video player.   Any known technique to apply a clear color to the background of these specific buttons?

**Comment by bre7** [comment]
Dupe of #98 

Similar to #74 #102

**Comment by bre7** [comment]
Check #98 for a workaround
