### ISSUE TITLE
Request for Swift 3.0 support

### ISSUE THREAD

**Issue by allenlinli** [ViccAlexander/Chameleon#155]
I am using ChameleonFramework (2.1.0), but it doesn't support Swift 3.0.
Is there anyone upgrading Chameleon?

Cheers.

**Comment by bre7** [comment]
Dupe #150. Please use the search function before submitting a new issue.

**Comment by allenlinli** [comment]
Sorry mate, I'll do the search next time.

**Comment by allenlinli** [comment]
I am sorry, I will do the search next time. Thanks.
