### ISSUE TITLE
Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Only RGBA or White color spaces are supported in this situation.'

### ISSUE THREAD

**Issue by pableiros** [ViccAlexander/Chameleon#159]
I can't use gradients color when I open external view controllers.
I saw it is a closed issue saying something like this but it doesn't solve my problem, I search a lot on Stackoverflow and I nothing works.

I set gradient primary color like this:
```swift
    extension UIColor {
        convenience init(netHex: Int) {
            self.init(red: (netHex >> 16) & 0xff, green: (netHex >> 8) & 0xff, blue: netHex & 0xff)
        }
    }

    static let primaryGradientColor: UIColor = {
        let sizeLength = UIScreen.mainScreen().bounds.size.height * 2
        let defaultNavigationBarFrame = CGRectMake(0, 0, sizeLength, 64)
        let colors = [UIColor(netHex: 0x176E8E), UIColor(netHex: 0x205784), UIColor(netHex: 0x1C4C74)]
        return GradientColor(.LeftToRight, frame: defaultNavigationBarFrame, colors: colors)
    }()

    Chameleon.setGlobalThemeUsingPrimaryColor(primaryGradientColor,
                                                  withSecondaryColor: UIColor.clearColor(),
                                                  andContentStyle: UIContentStyle.Light)
```
But when I open a `SFSafariViewController` for example:
```swift
     let safariViewController = SFSafariViewController(URL: url)
     self.presentViewController(safariViewController, animated: true, completion: nil)
```
The app crash and I get this error:
>
    Assertion failure in -[UICGColor encodeWithCoder:], /BuildRoot/Library/Caches/com.apple.xbs/Sources/UIKit_Sim/UIKit-3600.5.2/UIColor.m:1549
    Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Only RGBA or White color spaces are supported in this situation.'

**Comment by bre7** [comment]
Not related to Chameleon as far as I can see. The exception is caused by an incorrect parameter. Check #132 and also try using HEAD in your Podfile
