### ISSUE TITLE
Cannot use Chameleon with Carthage for objective-C project

### ISSUE THREAD

**Issue by haithngn** [ViccAlexander/Chameleon#160]
Hi,
I'm using Chameleon install by Carthage for my Objective-C project, my code:
`self.view.backgroundColor = FlatGreen;`
App crashed and the xcode said:
+[UIColor flatGreenColor]: unrecognized selector sent to class

**Comment by bre7** [comment]
Could you try using CocoaPods or cloning the repo ? First we need to know if it's related to Carthage or the lib.

**Comment by hailcl** [comment]
@bre7 ,
I tried to add Chamelon manual, it's work.

**Comment by bre7** [comment]
Then it's something related to Carthage

**Comment by KingInfinity** [comment]
Having same problem with Cocoapods

**Comment by bre7** [comment]
I've used Chameleon with Swift 3 and CP so you might be missing a step. Try creating a new project and adding Chameleon to it, if it works then it's related to your specific project.

**Comment by KingInfinity** [comment]
I think CP was just caching an older version of Chameleon from Swift 2, (I had installed the wrong version before, and I changed in Podfile and ran `pod install`, but it still didn't work). I tried running `pod update`, with  `pod 'ChameleonFramework/Swift', :git => 'https://github.com/ViccAlexander/Chameleon.git'` in Podfile, but version is still 2.1. How do I get version 2.2?

**Comment by bre7** [comment]
2.1 is the last published version. Try using HEAD like it's recommended in the readme:
```ruby
pod 'ChameleonFramework/Swift', :git => 'https://github.com/ViccAlexander/Chameleon.git'
```

**Comment by KingInfinity** [comment]
That is exactly what is in my Podfile, and I was confused because in Releases it says version 2.2.0.

**Comment by bre7** [comment]
Try using pod update. Are you able to "import ChameleonFramework" ?

**Comment by KingInfinity** [comment]
I've executed `pod update` and `pod install` several times. `import ChameleonFramework` has no errors.

**Comment by bre7** [comment]
Are you able to share the project ? Or share access to the repo ? It seems like something related to your project and not Chameleon
