### ISSUE TITLE
Issue with using Theme and UISearchBar Scope bar

### ISSUE THREAD

**Issue by arsanjani** [ViccAlexander/Chameleon#161]
Hi there
When i used Chameleon.setGlobalThemeUsingPrimaryColor, Scope bar of UISearchBar not showing because of same color of background and foreground in  UISegment inside of uisearchbar

BTW i'm using swift version

![thumb_img_0036_1024](https://cloud.githubusercontent.com/assets/8726637/20317794/cd7fc334-ab7c-11e6-8e25-acfa443f8202.jpg)

**Comment by bre7** [comment]
Similar to #98 (check workaround) #74 #102
