### ISSUE TITLE
How Can I remove Chameleon Pallete from my xCode

### ISSUE THREAD

**Issue by infinZero** [ViccAlexander/Chameleon#162]

**Comment by bre7** [comment]
Not related to the library but macOS.

https://encrypted.google.com/search?hl=en&q=remove+palette+from+macos
->
http://stackoverflow.com/questions/11386513/how-to-create-osx-clr-palette-files
->
http://www.robinwood.com/Catalog/Technical/OtherTuts/MacColorPicker/MacColorPicker.html
>"To Remove an Entire List"
