### ISSUE TITLE
issues in iOS10

### ISSUE THREAD

**Issue by infinZero** [ViccAlexander/Chameleon#163]
I am using Chameleon colors for the first time. & I am so excited for using these colors in my next comping projects but  there are more than 7 issues in iOS10 xCode 8.1 version, when I build & run my program it giving me following issues. 

1.  in `UIAppearance+Swift.m` file there is a line     `return [self appearanceWhenContainedIn:`
where it giving me issue that the appearanceWhenContainedIn is deprecated in iOS 9.0 use `+appearanceWhenContainedInInstancesofClasses:` instead so I changed that specific word but it giving error in bellow third line of the array             `count > 2 ? containers[2] : nil,`
I am attaching snapshot with this specific issue highlighted. please take a look
![screen shot 2016-11-17 at 12 23 40 pm](https://cloud.githubusercontent.com/assets/14030777/20380137/04910572-acc2-11e6-9f2d-45774af7dfb3.png)

2. there are several more issues (6 issues) coming from commented lines, I am not sure why xCode behaving like this i.e giving issues in comments of your files. 

please take  a look 

![screen shot 2016-11-17 at 12 25 33 pm](https://cloud.githubusercontent.com/assets/14030777/20380181/5198e880-acc2-11e6-9a60-b7471fb4bf8d.png)
![screen shot 2016-11-17 at 12 25 45 pm](https://cloud.githubusercontent.com/assets/14030777/20380182/521e4156-acc2-11e6-8f40-c79af7415ce5.png)

So Please Suggest some better solution that how to remove these issues.... 
Thanks

**Comment by bre7** [comment]
Errors are pretty self-explanatory. First one is a deprecation notice with a solution already in the message itself and the others related to code doc. Send a PR if you want or wait for a fix (they aren't high priority, for the time being)

**Comment by infinZero** [comment]
@bre7  I knows well the first one is for deprecation & also having its solution already but you've not read my issue completely. 
actually when I follow with deprecation message solution, it also giving me error in its below array. not in this function declaration line. please read my above first point completely.

**Comment by bre7** [comment]
What you tried to say was that you tried to fix the deprecation but hit an error after doing so ?
