### ISSUE TITLE
Color from Image inside Collection View Cell

### ISSUE THREAD

**Issue by viral-etymon** [ViccAlexander/Chameleon#168]
I have Image inside CollectionViewCell and using that image I am set the background of the cell. I am using ColorsFromImage(image, isFlatScheme) method to extract color in collectionview's cellForItemAt method. 

Problem is that by using this I am facing App lag issue while scrolling collection view. Below is my sample code.

```
func collectionView(_ collectionView: UICollectionView, cellForItemAt indexPath: IndexPath) -> UICollectionViewCell {                        
            let cell = collectionView.dequeueReusableCell(withReuseIdentifier: "movieCell", for: indexPath) as! cvSearchCollectionViewCell
            
            cell.lblTitle.text = movieList[indexPath.row].title
            
            let image = UIImage(named: "backdrop_nomovie")
            let url = URL(string: movieList[indexPath.row].backdrop_path)!                        
            cell.imgImage.kf.setImage(with: url, placeholder: image, completionHandler: {
                (image, error, cacheType, imageUrl) in
                if image != nil {
                    ////Below code is lagging my scroll
                    let colors = ColorsFromImage(image!, withFlatScheme: true)
                    if colors.count > 0 {
                        cell.bgView.backgroundColor = colors[colors.count - 2]
                        cell.lblTitle.textColor = ContrastColorOf(cell.bgView.backgroundColor!, returnFlat: true)
                    }
                }
            })                                                
            return cell
    }
```

Can you please suggest best way to do such task?

**Comment by bre7** [comment]
This isn't related to the library itself.

You might want to check out StackOverflow for similar cases, the issue is that the task at hand should be performed in the background (e.g: when the image is downloaded). Good luck 👍

**Comment by viral-etymon** [comment]
Does library support any background action. means when I try to fetch any color that task perform in background then I use result in main thread?

**Comment by bre7** [comment]
There are 2 methods for this:
https://github.com/ViccAlexander/Chameleon/blob/master/Pod/Classes/Objective-C/NSArray%2BChameleon.m#L100

Why not store the main color in your server ? Compute once, use it everywhere.

**Comment by viral-etymon** [comment]
Thanks that does some help. Starting to store color in and then using it. Thanks again
