### ISSUE TITLE
Gradients on Texts

### ISSUE THREAD

**Issue by otymartin** [ViccAlexander/Chameleon#169]
@ViccAlexander 
Is it possible to apply gradients on texts? eg UILabel? Navigation Bar title etc?

**Comment by bre7** [comment]
You need to work a bit with the generated image and the control:
https://google.com/search?hl=en&q=swift+image+as+text+mask
--> http://stackoverflow.com/questions/36516113/how-to-fix-the-gradient-on-text-when-using-an-image-in-swift-as-the-gradient-re
