### ISSUE TITLE
cocoapods download

### ISSUE THREAD

**Issue by FWBGitHub** [ViccAlexander/Chameleon#172]
Pre-downloading: `ChameleonFramework` from `https://github.com/ViccAlexander/Chameleon.git`
stay at this interface,i don't know

**Comment by bre7** [comment]
CP issue, not Chameleons. Check their blog/twitter next time ;)

https://twitter.com/CocoaPods/status/836707142941945858
> http://CocoaPods.org  and related services (including Trunk) are currently unavailable due to the Heroku outage (https://status.heroku.com/incidents/1059 )
