### ISSUE TITLE
UIStatusBarStyleContrast doesnt work

### ISSUE THREAD

**Issue by otymartin** [ViccAlexander/Chameleon#176]
@ViccAlexander 
self.setStatusBarStyle(UIStatusBarStyleContrast)

I set this in my `viewDidLoad`

I have a view whos background is a UIImageView taking up the whole screen. So naturally the statusbar color I expect to change according to the darkness or lightness of the underlying photo but thats not the case.

My info.plist has viewcontroller based statusbar set to YES

**Comment by bre7** [comment]
You might want to check the source code: https://github.com/ViccAlexander/Chameleon/blob/master/Pod/Classes/Objective-C/UIViewController%2BChameleon.m#L123

Image color detection is ammong Chameleon's status bar style use case

**Comment by otymartin** [comment]
@bre7 
I'm having a hard time following the logic in that link.
Does it contrast according to view.backgroundcolor? or the background color of the foremost view in my viewhireachy? Would appreciate some clarification

**Comment by bre7** [comment]
Top sub-view for viewcontroller.view

https://github.com/ViccAlexander/Chameleon/blob/62a377fec7c8fc39deb65ab8b46dce6e40250676/Pod/Classes/Objective-C/UIView%2BChameleonPrivate.m#L31

**Comment by otymartin** [comment]
@bre7 thanks :)
