### ISSUE TITLE
Use Of Undeclared Type 'AkiraTextField'

### ISSUE THREAD

**Issue by deborahelizabethpadilla** [ViccAlexander/Chameleon#184]
Hi there!

I'm receiving this error within my outlets in my form view controller. It works fine in my login view controller. Not sure if this is a bug or what, but it's not allowing me to compile. My class and module is connected in storyboard. I tried reconnecting my outlets. Thanks in advance.

**Comment by bre7** [comment]
Hey,

I'm sorry to say but it's unrelated to our framework (AkiraTextField doesn't even exist in Chameleon)
