### ISSUE TITLE
Documentation Issue Warnings

### ISSUE THREAD

**Issue by deborahelizabethpadilla** [ViccAlexander/Chameleon#189]
I'm receiving warnings in my project (i.e., Documentation Issue: Parameter 'excludedColors', 'isFlat', 'color' not found in the function declaration, etc etc). These warnings seem to be hidden in the Objective-C files.

I'm working with Swift and CocoaPods. Is there any solution to get rid of these warnings?

**Comment by SebastianKumor** [comment]
Got the same warnings. Funny thing is I got them just few days ago without updating anything but I was using chameleon for few months already.

**Comment by onlyexcellence** [comment]
Same.

**Comment by deborahelizabethpadilla** [comment]
Did anybody figure out the fix? I can't seem to find a solution still. Any help would be appreciated!

**Comment by deborahelizabethpadilla** [comment]
Ok, so, I imported Chameleon into Storyboard and removed the framework from the pod. The warnings went away when I did this instead. I'm not sure if that will solve anything on your end, but this seemed to work for me and be a temporary solution. Good luck!

**Comment by SebastianKumor** [comment]
I just reimplemented the parts of the framework I needed and removed it as well.

**Comment by bre7** [comment]
Xcode9 isn't showing those warnings.
