### ISSUE TITLE
How to import chameleon inside a private pod

### ISSUE THREAD

**Issue by SIGMAMobile** [ViccAlexander/Chameleon#194]
I'm in trouble trying to include Swift 3 version in a podspec file. When I try to validate my podspec it throws some errors. Seems that is searching for an older release. I wonder if any know any solution or workaround because in the podspec I can't set the git path.

eg:
` - ERROR | [iOS] xcodebuild: Returned an unsuccessful exit code. You can use `--verbose` for more information.
    - ERROR | [iOS] xcodebuild:  ChameleonFramework/Pod/Classes/Swift/ChameleonShorthand.swift:53:12: error: 'init(randomFlatColorOfShadeStyle:)' has been replaced by 'init(randomFlatColorOf:)'
...`

Podspec: `s.dependency 'ChameleonFramework/Swift'`
PodFile: `pod 'ChameleonFramework/Swift', :git => 'https://github.com/ViccAlexander/Chameleon.git'`

Thx

**Comment by bre7** [comment]
Try with the latest code. Doesn't seem to be a question for our repo but SO maybe since it's related to CocoaPods and not Chameleon itself.
