### ISSUE TITLE
Update for Swift 4 please

### ISSUE THREAD

**Issue by MKGitHub** [ViccAlexander/Chameleon#197]
Update for Swift 4 please

**Comment by bre7** [comment]
PRs are welcome. Doubt there are many changes to be made.

**Comment by allenspicer** [comment]
Is this updated?

The imweihuang#1 version says it is merged with the main branch but the default ChameleonFramework (2.1.0) throws lots of Swift 4 related errors for me.  Running Xcode 9.1.

**Comment by ommeirelles** [comment]
Same here @allenspicer.
Xcode 9.4 here and chameleon is throwing a lot of errors...

**Comment by Wildchild9** [comment]
I have Xcode 10 and chameleon is also throwing a lot of errors.
