### ISSUE TITLE
Question about dynamic framework

### ISSUE THREAD

**Issue by Andy0570** [ViccAlexander/Chameleon#199]
I noticed that you recommend using the dynamic library to add Chameleon：

```
use_frameworks!

pod 'ChameleonFramework'
```

What happens if I do not use the dynamic library to add the chameleon? Or what features are missing?

thank you very much ！

**Comment by bre7** [comment]
This is related to CocoaPods and not Chamelon. More info: https://encrypted.google.com/search?hl=en&q=cocoapods%20use_frameworks
