### ISSUE TITLE
IBdesignable class for setting colors via storyboard?

### ISSUE THREAD

**Issue by remzr7** [ViccAlexander/Chameleon#20]

**Comment by beeth0ven** [comment]
Yes,Lecture 5 and 6 teaches us the method,You can downloads the project <Happiness L6.zip> to see.
http://web.stanford.edu/class/cs193p/cgi-bin/drupal/

**Comment by VAlexander** [comment]
Thanks @remzr7 & @beeth0ven  I'll definitely look over this on the weekend. In the meantime, is there any specific use cases you'd like to see this implemented for? If you simply want to set colors, you can use the Color Palette I built for mac: [Chameleon Storyboard Palette](https://github.com/VAlexander/Chameleon#storyboard-add-on-)

However if you'd like Chameleon to expose other properties such as a `flatify` boolean, or a `randomColor` option in storyboard, it may be possible.

**Comment by beeth0ven** [comment]
Chameleon Storyboard Palette is a great framework, I like it very much.
Thanks.
