### ISSUE TITLE
Warnings in Xcode 9.3

### ISSUE THREAD

**Issue by uetcis** [ViccAlexander/Chameleon#211]
When I try to build my project in Xcode Version 9.3 beta (9Q98q), the compiler shows warnings:
<img width="376" alt="image" src="https://user-images.githubusercontent.com/25654046/35477238-fc8debd4-03f9-11e8-9254-d18598f6454b.png">

**Comment by yasinkavakli** [comment]
Any updates on this?

**Comment by denys-meloshyn** [comment]
It would be nice to know how to fix it 😶

**Comment by shangmaumau** [comment]
Replace #if by #ifdef can solve all the warnings.

**Comment by filipealva** [comment]
+1

**Comment by TheBaldNerd** [comment]
I edited around 3 or 4 entries like this and it removed all the Warnings.  Nice job @shangleixun
