### ISSUE TITLE
NSInvalidArgumentException

### ISSUE THREAD

**Issue by Will-1-Am** [ViccAlexander/Chameleon#228]
Xcode 10
Everything was working really well until I imported ChameleonFramework and ran code in simulator.  

I commented out the import and changed the colours to the standard iOS colours and everything worked again.

Then I uncommented the import but left the standard colours and the app worked fine.
I changed the colours to the Chameleon colors and the app crashes with the following "dump".
Any ideas how I can fix this?

The app also crashes on physical iPhone.
 
"Dump":
2018-10-17 15:32:56.245874+0300 Flash Chat[2363:523243] +[UIColor flatOrangeColor]: unrecognized selector sent to class 0x1e9ac1798
2018-10-17 15:32:56.255673+0300 Flash Chat[2363:523243] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '+[UIColor flatOrangeColor]: unrecognized selector sent to class 0x1e9ac1798'
*** First throw call stack:
(0x1b09b7ef8 0x1afb85a40 0x1b08d41fc 0x1b09bd810 0x1b09bf4bc 0x100574d2c 0x100575298 0x1dd9e1f30 0x1dd9e2478 0x1dd9adbfc 0x1dd9cbae8 0x1ddc5ff44 0x1b4f99a34 0x1b4f9e9c4 0x1b4efd9d4 0x1b4f2c2f4 0x1b4f2d15c 0x1b0945b94 0x1b0940828 0x1b0940dc8 0x1b09405b8 0x1b2bb4584 0x1dd7bcbc8 0x10057284c 0x1b0400b94)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by Will-1-Am** [comment]
Reinstalling the ChameleonFramework pod fixed the issue above but another buildtime issue described as "Enumeration value 'kCGColorSpaceModelXYZ' not handled in switch" has arisen.  The application appears to be unaffected - in other words the crashing stopped.

**Comment by wel51x** [comment]
re: kCGColorSpaceModelXYZ

Newbie here: I'm having the same problem. Is the best way to handle this as kCGColorSpaceModelUnknown?

Thanks.

**Comment by gilthiago** [comment]
Yes.. same here.. deleted from Podfile pod 'ChameleonFramework', run pod install,, add it again,, and rerun pod install. solved...

**Comment by Hesham-Salama** [comment]
> Yes.. same here.. deleted from Podfile pod 'ChameleonFramework', run pod install,, add it again,, and rerun pod install. solved...

Didn't work, using Xcode 10.0
