### ISSUE TITLE
Function produces expected type 'UIColor'; did you mean to call it with '()'?

### ISSUE THREAD

**Issue by RSickenberg** [ViccAlexander/Chameleon#242]
Not compliant with Xcode 11.

**Comment by PavelVaskou** [comment]
the same

**Comment by luckychris** [comment]
same here

**Comment by JustinKalicharan** [comment]
Bump, same here.  Anyone got any good work arounds?

**Comment by luckychris** [comment]
you can try my branch, for me it works:

https://github.com/luckychris/Chameleon

**Comment by luckychris** [comment]
> Not compliant with Xcode 11.

you can try my fork - for me it works: https://github.com/luckychris/Chameleon

**Comment by JustinKalicharan** [comment]
> you can try my branch, for me it works:
> 
> https://github.com/luckychris/Chameleon

Sir, this works perfectly!  Thanks for providing a clean working branch!

**Comment by luckychris** [comment]
> > you can try my branch, for me it works:
> > https://github.com/luckychris/Chameleon
> 
> Sir, this works perfectly! Thanks for providing a clean working branch!

Thank you. It was a pleasure.
Can you give me a star? It would be my very first one ☺️

**Comment by JustinKalicharan** [comment]
> > > you can try my branch, for me it works:
> > > https://github.com/luckychris/Chameleon
> > 
> > 
> > Sir, this works perfectly! Thanks for providing a clean working branch!
> 
> Thank you. It was a pleasure.
> Can you give me a star? It would be my very first one ☺️

Done!  I would have given you more if I could.  Thanks again; keep up the really good work!

**Comment by RomainPln** [comment]
> > > > you can try my branch, for me it works:
> > > > https://github.com/luckychris/Chameleon
> > > 
> > > 
> > > Sir, this works perfectly! Thanks for providing a clean working branch!
> > 
> > 
> > Thank you. It was a pleasure.
> > Can you give me a star? It would be my very first one ☺️
> 
> Done! I would have given you more if I could. Thanks again; keep up the really good work!

Saved my time, got my star too. Thanks.

**Comment by luckychris** [comment]
> > > > > you can try my branch, for me it works:
> > > > > https://github.com/luckychris/Chameleon
> > > > 
> > > > 
> > > > Sir, this works perfectly! Thanks for providing a clean working branch!
> > > 
> > > 
> > > Thank you. It was a pleasure.
> > > Can you give me a star? It would be my very first one ☺️
> > 
> > 
> > Done! I would have given you more if I could. Thanks again; keep up the really good work!
> 
> Saved my time, got my star too. Thanks.

Thank you!

**Comment by ismaiI1** [comment]
> > Not compliant with Xcode 11.
> 
> you can try my fork - for me it works: https://github.com/luckychris/Chameleon

How can update Chamelon to your fork using podfile?

Edit : Sorry, I Found. Thanks for your fork 👍 I will give you a star :)

**Comment by Alqueraf** [comment]
Thanks @luckychris. For reference, to include his fork on the podfile just change it to:
`pod 'ChameleonFramework/Swift', :git => 'https://github.com/luckychris/Chameleon.git', :inhibit_warnings => true`

**Comment by RSickenberg** [comment]
Many thanks guys! 

Was a pleasure to deal with you!

**Comment by Sunsimiao** [comment]
> you can try my branch, for me it works:
> 
> https://github.com/luckychris/Chameleon

Really good job! 
I want to give you 10 stars!
Hope you can maintain the Chameleon!
