### ISSUE TITLE
I want to take the time to thank the following individuals...

### ISSUE THREAD

**Issue by ViccAlexander** [ViccAlexander/Chameleon#29]
I want to take the time to thank the following individuals...

@aekwan @alist @bre7 @cascio @ddwang @jmhooper @peacemoon @saullopez @sfader @smokyonion & @jherran

I've been busy working on a separate project for the last couple of months, which prevented me from being as involved with Chameleon as I would have liked. I feel like I never had the change to truly thank all of you for taking the time to check out Chameleon and contribute to it. Your contributions / pull requests / comments / and advice have definitely helped out. Cheers to all of you for truly being amazing! 🍻🎉

I figured the least I could do was add all of you to the [Special Thanks](https://github.com/VAlexander/Chameleon#-special-thanks) section, while also giving you credit for fixes in the [Change Log](https://github.com/VAlexander/Chameleon#-change-log) section. 

![Thank you](http://media.giphy.com/media/6tHy8UAbv3zgs/giphy.gif)

Again thank you for helping out, and good luck on all your projects!  

🎈🎈🎉🙌😃🍻👏🎊🎈🎈

Best,
Vicc

**Comment by bre7** [comment]
Thank you, for releasing such a great component Vic ;)

**Comment by ViccAlexander** [comment]
@bre7 No worries! I'm actually planning on a huge 2.0 release later this summer in hopes of simplifying the library some more, while also adding some of the planned features! It'll be exciting.

**Comment by bre7** [comment]
Can't wait !!! (For real haha)
