### ISSUE TITLE
Set up UIAppearance globally?

### ISSUE THREAD

**Issue by romanr** [ViccAlexander/Chameleon#3]
I read through documentation twice and there's no mention of setting global UIAppearance.
I'd like to set colors once in AppDelegate globally and not insert 'set color' into each and every one view controller.

What is the best practice for setting global UIAppearance or is there an example?

**Comment by bre7** [comment]
Something like this: https://github.com/dphans/DPTheme/blob/master/DPTheme/DPTheme.swift

**Comment by ViccAlexander** [comment]
@bre7 Thanks for your suggestion! Actually I've been working on Chameleon 2.0 for the past few weeks, and this was one of the first few things I already built! :sunglasses: I'm just waiting on one more feature, and I'll be releasing it soon! :) Thanks for keeping it :100:  and holding down the fort in the meantime! Cheers!

**Comment by bre7** [comment]
:wink: np

**Comment by ViccAlexander** [comment]
Just added to Chameleon 2.0 🎉
