### ISSUE TITLE
Cocoapods alert for objc project

### ISSUE THREAD

**Issue by qiaoyan** [ViccAlexander/Chameleon#30]
Hi, 
is there any configuration in pod's file can define version for objc?
From Cocoapods:

``` ruby
[!] Pods written in Swift can only be integrated as frameworks; this feature is still in beta. Add `use_frameworks!` to your Podfile or target to opt into using it.
```

**Comment by bre7** [comment]
There is a way using subspecs like [QueryKit.podspec](https://github.com/QueryKit/QueryKit/blob/master/QueryKit.podspec) for example. The current solution would be to use Chameleon 1.1.2

**Comment by qiaoyan** [comment]
Thanks bre7,  the following line resolve this issue temporarily:
pod 'ChameleonFramework', :git => "https://github.com/VAlexander/Chameleon.git", :tag => "1.1.2"

**Comment by ViccAlexander** [comment]
@qiaoyan @bre7 Let me look into this. I'll post any updates here.

**Comment by bre7** [comment]
@qiaoyan Or pod 'ChameleonFramework', ,1.1.2'

**Comment by ViccAlexander** [comment]
@bre7 is right, you could simply use:

``` ruby
pod 'ChameleonFramework', '1.1.2'
```

In the mean time I'm going to try to fix this. @bre7 Would the smartest thing to do is create a new swift branch and drop the swift files there? Or would using subspecs do the job?

**Comment by bre7** [comment]
I think they would both do the trick. There's a third option: two separate specs and single branch like Realm does [realm-cocoa](https://github.com/realm/realm-cocoa?files=1)

**Comment by ViccAlexander** [comment]
So I decided that the best thing to do for now is pursue the third option suggested by @bre7. I've separated objective-c and swift files into different folders, and plan on creating a separate spec for swift installations. At the moment the latest version (1.2.0) should install without a problem for Objective-C projects.

You can go back to simply using:

``` ruby
pod 'ChameleonFramework'
```

Later tonight I'll look into creating one for Swift.

**Comment by ViccAlexander** [comment]
On second thought, it seems a bit premature to create a pod spec for Swift when `pod 'ChameleonFramework'` works just as well for both. Perhaps if the library was completely ported over to Swift, would it make more sense. Maybe it's something that can happen if people truly want this once 2.0 is out, but I can't see much added benefit. 

With that said, installation and usage should be just as easy for both languages at the moment. I updated the [Installation section](https://github.com/ViccAlexander/Chameleon#installation) to cover both Objective-C and Swift, and even added Swift examples throughout the rest of the documentation as well.

**Comment by bre7** [comment]
I was gonna ask if you wanted swift examples :) Extension for "UIStatusBarStyle Methods" would be another way, I'll push it in a sec.

**Comment by ViccAlexander** [comment]
Thanks @bre7! I'll look at the pull request in a bit.
