### ISSUE TITLE
Error in swift project

### ISSUE THREAD

**Issue by carnegepg** [ViccAlexander/Chameleon#33]
I read the documentation and did the installation for cocoapods and import for my project the *ChameleonShorthand.swift*, when build the project give me the following error:

```
/ChameleonShorthand.swift:41:38: Use of undeclared type 'UIShadeStyle'
/ChameleonShorthand.swift:49:35: Use of undeclared type 'UIGradientStyle'
/ChameleonShorthand.swift:65:36: Use of undeclared type 'ColorScheme'
/ChameleonShorthand.swift:58:12: Use of unresolved identifier 'ChameleonStatusBar'
```

Another alert that the xcode this giving is:

```
/ChameleonFramework/Pod/Classes/Objective-C/UIColor+Chameleon.m:374:9: Value stored to 'backgroundColor' is never read
```

Can you help me?
Thanks a lot

**Comment by bre7** [comment]
Xcode version ?

**Comment by carnegepg** [comment]
Xcode 6.3.2 (6D2105) with swift 1.2

**Comment by bre7** [comment]
Mmmh, it shouldn't happen...Let me check with a new project again

**Comment by bre7** [comment]
Thanks for catching my mistake :) @ViccAlexander should accept the PR but meanwhile, to fix it just add:
```swift
import ChameleonFramework
````
to the swift file

**Comment by carnegepg** [comment]
Thanks... :smile:

**Comment by ViccAlexander** [comment]
Thanks for catching this @carnegepg. I'm glad @bre7 figured it out (BTW Thanks for stepping in). I've accepted the pull request, so everything should be pretty straightforward now. :sunglasses:  :+1:
