### ISSUE TITLE
I get the error No such module on import ChameleonFramework

### ISSUE THREAD

**Issue by Lucas-gronlund** [ViccAlexander/Chameleon#35]
I get the error "No such module" on import ChameleonFramework in the Swift file. I have done the manual installation. Any solution? (Also tried cleaning and rebuilding)

**Comment by bre7** [comment]
It should work, post your Podfile if you can.

**Comment by Lucas-gronlund** [comment]
I'm not able to use Cocoapods since im using the El capitan beta. So my problem is importing just the manual way.
