### ISSUE TITLE
Add Carthage support

### ISSUE THREAD

**Issue by bre7** [ViccAlexander/Chameleon#37]

**Comment by benwoodward** [comment]
+1

**Comment by ViccAlexander** [comment]
Thanks for the suggestion. Personally, I haven't tried Carthage, but I'll definitely look into it this weekend! :sunglasses:

**Comment by ViccAlexander** [comment]
Chameleon will support Carthage in the upcoming **2.0** release. :smiley:

**Comment by benwoodward** [comment]
Great! Thanks.

**Comment by NicholasTD07** [comment]
@ViccAlexander check out this PR #45. I have done this a while ago, so might need to resolve some merge conflicts.
