### ISSUE TITLE
Update for Swift 2.0 and IOS 9?

### ISSUE THREAD

**Issue by carnegepg** [ViccAlexander/Chameleon#38]
I wonder when will have an update for the swift 2.0 and IOS 9.

Thanks.

**Comment by bre7** [comment]
I'm pretty sure it works for swift 2 since there are only simple functions. I can be wrong though. As Vic said, he's working on v2.0 of the framework otherwise I'd update it if needed.

**Comment by ViccAlexander** [comment]
Thanks @bre7 for helping to manage Chameleon! Really appreciate it. I'm on a trip right now, but will try to update cocoa pods asap!!! :smiley:

**Comment by dankiiing** [comment]
@ViccAlexander your framework is fantastic, how do I use in in swift ? I have imported it as a cocoapod and not sure what to do next, do I create a bridge header ?

**Comment by bre7** [comment]
You can either install the pod and copy the swift file manually, or wait till Vic accepts the new PR so you only need to do:
```ruby
platform :ios, "8.0"

use_frameworks!

pod 'ChameleonFramework/Swift'
```

**Comment by ViccAlexander** [comment]
Just updated the cocoa pod and the readme thanks to @bre7's help! Everything should be straightforward now!!! :sunglasses: Enjoy!

**Comment by carnegepg** [comment]
Thanks guys, sorry for the delay to answer, I'll test now. :smile:

**Comment by ViccAlexander** [comment]
@carnegepg No worries. I'm glad you've found Chameleon useful! :smiley:
