### ISSUE TITLE
Problem adding files

### ISSUE THREAD

**Issue by ad-moh** [ViccAlexander/Chameleon#40]
I'm having problems adding the files to my swift project. I keep getting errors in the short hand class. Can you please explaining a little bit more on how to integrate it?
Thank you

**Comment by bre7** [comment]
Hi ad-moh, you don't need to add any files manually anymore. Are you using CocoaPods?

**Comment by ad-moh** [comment]
No, I'm not using CocoaPods. You mean the folder named pod or the whole project folder?
Sorry i'm still new at this.

**Comment by bre7** [comment]
The folder names Pod.

**Comment by ad-moh** [comment]
Yeah that's what I did but I keep getting errors in the ChameleonShorthand.swift file.
![screen shot 2015-07-22 at 8 30 20 am](https://cloud.githubusercontent.com/assets/8908361/8825294/0c96fb62-304c-11e5-9625-53d7150b2c5e.png)

**Comment by bre7** [comment]
I'll give it a try later and let you know.

**Comment by ad-moh** [comment]
Alright. Thank you

**Comment by bre7** [comment]
Nevermind, the issue is because swift isn't loading the objc classes. You need to add the imports to your Bridging header.

**Comment by ad-moh** [comment]
Oh yeah, it didn't create a bridging header when i added. I guess I have to do that manually

**Comment by ad-moh** [comment]
It worked. You guys have a really cool library here. Thanks for everything

**Comment by ViccAlexander** [comment]
Awesome!
