### ISSUE TITLE
duplicate definition of category

### ISSUE THREAD

**Issue by TerryHug2305** [ViccAlexander/Chameleon#42]
I use  'EDColor' and 'ChameleonFramework' in pod, Could add a prefix to category  'CIELAB' on interface 'UIColor' ?
iphonesimulator/ChameleonFramework.framework/Headers/UIColor+CIELAB.h:33:12: warning: duplicate definition of category 'CIELAB' on interface 'UIColor'
@interface UIColor (CIELAB)

**Comment by bre7** [comment]
V2 should be here soon, otherwise Vic will fix it. (Or I'll PR later)

**Comment by ViccAlexander** [comment]
Sorry about that. Will do it over the weekend!

**Comment by TerryHug2305** [comment]
thanks，I very appreciate that

2015-08-27 8:06 GMT+08:00 Vicc Alexander <notifications@github.com>:

**Comment by bre7** [comment]
> Sorry about that. Will do it over the weekend. In fact maybe I'll look into prefixing all the classes.

Prefixing the categories is more than enough, doubt there will be collisions with other classes.

**Comment by TerryHug2305** [comment]
maybe you can use Travis CI to test Prefixing

2015-09-07 23:07 GMT+08:00 bre7 <notifications@github.com>:

**Comment by ViccAlexander** [comment]
@bre7 You're correct. I'm holding out on everything until 2.0. It's almost ready I promise.  

@TerryHug2305 I've never tried using Travis CI, but it seems like everyone is using it, and for good reason. I'll definitely check it out.

**Comment by bre7** [comment]
> @bre7 You're correct. I'm holding out on everything until 2.0. It's almost ready I promise.

:+1:

**Comment by ViccAlexander** [comment]
No longer should be a problem in `2.0` :smiley:
