### ISSUE TITLE
Updating Swift to 2.0

### ISSUE THREAD

**Issue by ViccAlexander** [ViccAlexander/Chameleon#46]
Hi @bre7!

Just updated Chameleon to 2.0. There might be some conflicts with Swift Macros though since several have been deprecated. It would be awesome if you can check it out real quick. Also if you have time, could you add some Swift examples for the new features in the documentation! Thanks!!! :smiley:

**Comment by bre7** [comment]
I was just reading the README :D Awesome update :+1: 

Don't bother merging the PR yet, I'll add the swift stuff in there and mention you when it's done ?

**Comment by ViccAlexander** [comment]
Thank you! Aww man I merged it right before lol yeah just let me know!

**Comment by bre7** [comment]
Hehe, no worries.

One thing, related to Objc...Do you prefer the non-generics version ? For instance, in **NSArray+Chameleon.h** it would be *better* to use `NSArray<UIColor *>` instead of `NSArray`

**Comment by ViccAlexander** [comment]
Is that now possible in ObjC? If so, specifying types would be better!

**Comment by ViccAlexander** [comment]
BTW Should I go ahead and merge the PR? Let me know when you're good. Also, it'll require a cocoa pods update as well right?

**Comment by bre7** [comment]
Yes and yes....I'll upgrade the remaining stuff in the readme this week probably. [New in Obj-C](https://developer.apple.com/library/prerelease/ios/documentation/DeveloperTools/Conceptual/WhatsNewXcode/Articles/xcode_7_0.html)

**Comment by ViccAlexander** [comment]
Thanks bre! Appreciate all the work you put into this!

**Comment by bre7** [comment]
Almost done (Only the shorthand methods for now, Swift only version is in the works but it will take a while)
