### ISSUE TITLE
v2 questions

### ISSUE THREAD

**Issue by bre7** [ViccAlexander/Chameleon#48]
1. Typo in the definition ? It's in the `#pragma mark - Class Methods` section
2. In `UIViewController+Chameleon.h` the method `flatify()` is empty (Line 97)
3. In `findColorsOfImage(...)`, won't the NSArray and NSCountedSet have the same colors ?

**Comment by ViccAlexander** [comment]
@Bre7 

1. In what file is the typo in?
2. I ended up removing support for the `flatify` method. It wasn't as perfect as I wanted it to be, and with the new support for themes, I figured it wouldn't be as useful.
3. Not exactly. The NSCountedSet holds a color for every single pixel. I then do some processing (ensure they all have a minimum saturation tolerance) and sort them by most occuring to least occurring. Eventually only 5 will end up in the `NSArray.`

**Comment by bre7** [comment]
I think 1 was in one of the categories named Private.

Tests incoming also.  I'll start with your code as a baseline for now.

**Comment by bre7** [comment]
```objectivec
if (abs(r - g < 0.03f && fabs(r - b) < 0.03f)) {
```

`abs` of a bool ?

**Comment by ViccAlexander** [comment]
Where is that line located?

**Comment by bre7** [comment]
https://github.com/ViccAlexander/Chameleon/blob/338ff86ed7a8f8cf0fed578215742605a67391ce/Pod/Classes/Objective-C/UIColor%2BChameleonPrivate.m#L103

**Comment by ViccAlexander** [comment]
Oh right. `abs` isn't a bool. What that line is doing is checking if a certain color is distinct enough from another. What it is doing specifically is checking if the difference of several values is at least 0.03 (tolerance). If it is, it determines that the two colors are distinct, otherwise it returns `no`. It does this several times checking for different things each time.

**Comment by bre7** [comment]
Shouldn't `UIColor.blueColor().flatten()` be the same as `FlatBlue()` or `FlatBlueDark()` ? Or should nearestColor return another thing ?

**Comment by ViccAlexander** [comment]
1. Yes and no. What it does is it tries to find the closest "Flat Color" to the provided color. 'Flattening' blue has always been a bit of a problem since the human eye tends to favor it differently than computers, so it usually returns a purplish flat for that specific blue. It worked exactly the same as the deprecated`flatVersionOf:` method.

2. Ahh you're right! Nice catch!

**Comment by bre7** [comment]
Why have a separate parameter for alpha instead of using color's alpha, in  `+ (UIColor *)colorWithComplementaryFlatColorOf:(UIColor *)color withAlpha:(CGFloat)alpha`

**Comment by ViccAlexander** [comment]
1. To answer your first question, I figured it would be easier for developers who also wanted to change the alpha of the new color, to do so in one call. I've found myself having to do that a few times, and so this definitely made that easier. However I'm sure you've seen it, but there's also a simple version of that method: `+ (UIColor *)colorWithComplementaryFlatColorOf:(UIColor *)color`

3. Actually `gradientImage` is a property added to `UIImage` to hold the gradient a user creates when using `colorWithGradient...` It's not meant to be directly set by the user (More like a storage area for Chameleon). If anything it should be readonly though. I'll update it. 

4. Let me take a look and I'll get back to you on this!

**Comment by ViccAlexander** [comment]
@bre7 Seeing how much you've helped out in the past few weeks, I've added you as a collaborator to makes things easier! Thanks for all your help :100: :smiley:

**Comment by bre7** [comment]
😉😁 ty. I've enjoyed working with this framework quite a lot

**Comment by ViccAlexander** [comment]
No worries! I trust your input. :+1:

**Comment by jlama** [comment]
Shouldn't `if (abs(r - g < 0.03f && fabs(r - b) < 0.03f))` actually be `if (abs(r - g) < 0.03f && fabs(r - b) < 0.03f)` ?

**Comment by ViccAlexander** [comment]
@jlama At first glance it looks like your suggestion should be used, but apparently Xcode throws the following warning if we do that:

> /Users/...UIColor+ChameleonPrivate.m:103:13: Using floating point absolute value function 'fabs' when argument is of integer type

That is why we're using `abs` instead of `fabs`.

**Comment by jlama** [comment]
What I wanted to point out is the missing closing ) after abs(r - g
`if (abs(r - g < 0.03f && fabs(r - b) < 0.03f))`
vs
`if (abs(r - g) < 0.03f && fabs(r - b) < 0.03f)`

**Comment by ViccAlexander** [comment]
Ahh I see. Thanks @jlama. It seems that as of 2.0.4 it's been fixed. Appreciate it though.

**Comment by jlama** [comment]
It doesn't seem so: https://github.com/ViccAlexander/Chameleon/blob/master/Pod/Classes/Objective-C/UIColor%2BChameleonPrivate.m#L103

**Comment by ViccAlexander** [comment]
Oh wow you're right. It should be fixed in 2.0.5.
