### ISSUE TITLE
Wrong navigation bar color

### ISSUE THREAD

**Issue by annehiro** [ViccAlexander/Chameleon#51]
The following line in AppDelegate makes navigationBar background and text color white. 
        `Chameleon.setGlobalThemeUsingPrimaryColor(FlatMint(), withSecondaryColor: FlatBlue(), andContentStyle: UIContentStyle.Contrast)`

**Comment by bre7** [comment]
Mmmh, `ContrastColor`seems to be the problem.

**Comment by bre7** [comment]
This line is the problem:
```objectivec
[[UINavigationBar appearance] setBackgroundImage:[UIImage new] forBarMetrics:UIBarMetricsDefault];
```

**Comment by annehiro** [comment]
Okay, that worked for me. But I had to make the change in Chameleon.m.

**Comment by bre7** [comment]
Fix will pushed soon ;)

**Comment by annehiro** [comment]
Thanks!

**Comment by ViccAlexander** [comment]
Thanks @bre7! Can you do a pull request with your fix?

**Comment by bre7** [comment]
Will do
