### ISSUE TITLE
flatten bug

### ISSUE THREAD

**Issue by bre7** [ViccAlexander/Chameleon#53]
`color.flatten` calls `colorWithFlatVersionFrom(self)`, then `[color getLightness:nil valueForA:nil valueForB:nil alpha:&colorAlpha];`. Inside `getLightness` there's this code:
```objectivec
*L = [LABValues[0] floatValue];
*A = [LABValues[1] floatValue];
*B = [LABValues[2] floatValue];
```
but they are all nil

**Comment by ViccAlexander** [comment]
I'll take a look!
