### ISSUE TITLE
setStatusBarStyle deprecated in iOS9

### ISSUE THREAD

**Issue by bre7** [ViccAlexander/Chameleon#55]
Ignoring it for now ?

Docs: [setStatusBarStyle:animated:](https://developer.apple.com/library/ios/documentation/UIKit/Reference/UIApplication_Class/#//apple_ref/occ/instm/UIApplication/setStatusBarStyle:animated:)

**Comment by ViccAlexander** [comment]
Yupp. Figured it'll be a while before they're completely removed from iOS. I'll think of a better approach soon.

**Comment by bre7** [comment]
appearanceWhenContainedIn was also deprecated in iOS 9

**Comment by ViccAlexander** [comment]
True. Definitely need to find an alternative way. Once we figure out all the other bugs, we can totally focus on this.
