### ISSUE TITLE
EXC_BAD_ACCESS Error

### ISSUE THREAD

**Issue by 99centsappdevelopment** [ViccAlexander/Chameleon#57]
I am getting an EXC_BAD_ACCESS error on the following line in UIColor+ChameleonPrivate:

        *L = [LABValues[0] floatValue];

(L = NULL)

Why is this? I installed manually, not with CocoaPods (I just dragged the files into my project and imported Chameleon.h - no other errors)

**Comment by 99centsappdevelopment** [comment]
This is only a problem, I have discovered, when for:

    [NSArray arrayOfColorsFromImage:img withFlatScheme:NO];

withFlatScheme = YES. There is no problem if it = NO

**Comment by bre7** [comment]
Yeah, there's an open issue already: Check #53. Fix was submitted, merge pending
