### ISSUE TITLE
Cocoapod Error: Chameleon.h not found

### ISSUE THREAD

**Issue by ViccAlexander** [ViccAlexander/Chameleon#60]
@bre7 I didn't want to move the `Chameleon.h` file you added just in case it broke any dependencies, however I added a copy back into the Pod folder to fix the error.

**Comment by ViccAlexander** [comment]
Updated to 2.0.2.2 and everything seems to be working correctly now.

**Comment by bre7** [comment]
Ohhh darn, forgot to fix the pod. The easiest solution would be to change the spec to `Chameleon_` instead of `Chameleon`

**Comment by ViccAlexander** [comment]
No worries I left everything as is, and just dropped Chameleon back in, which imports Chameleon_.h and all the other headers. It seems to be working perfectly now.

**Comment by bre7** [comment]
Awesome. Had to rename it to avoid issues in the dynamic library since there was a `Chameleon.h` already

**Comment by ViccAlexander** [comment]
No worries! So is everything good now? Didn't want to break anything.

**Comment by bre7** [comment]
I'll check tomorrow (later I guess) to be sure

**Comment by ViccAlexander** [comment]
Awesome let me know if there's anything I can do. I'm using it right now in a project and it seems to be working perfectly so I'll do the same! Thanks.

**Comment by MariamNers** [comment]
Hi! I am having the same kind of issue, my project is in swift and I added Chameleon folder to my project, did everything you mentioned in your docs and added #import "Chameleon.h" into my bridging header, but unfortunately it gives me this error : 'Chameleon_.h' file not found. What am I doing wrong?

**Comment by bre7** [comment]
Have you followed the instructions mentioned in the installation section: https://github.com/ViccAlexander/Chameleon#installation ?

**Comment by MariamNers** [comment]
Yes, I was actually adding it manually, but even when i add it via cocoa pods i still get "No such module 'ChameleonFramework''"

**Comment by bre7** [comment]
You might be doing something wrong. I've just tested both CocoaPods and Carthage with a new project and it worked.

**Comment by MariamNers** [comment]
Well, I dont normally use cocoa pods, nevertheless i retried it again, and now it gives me this error "Cannot load underlying module for 'ChameleonFramework'".. what am i doing wrong? I can see in my folder I do have a newly created workspace, but it still doesn't work.

**Comment by bre7** [comment]
I usually use Carthage. Your issue seems not to be related to Chameleon itself as far as I can tell. Check google, stackoverflow, or CocoaPods issues.

**Comment by MariamNers** [comment]
restarted my laptop without changing anything and it magically worked.... Xcode sorcery..

**Comment by iaMeteor** [comment]
try remove ~/Library/Developer/Xcode/DerivedData/* and rebuild
