### ISSUE TITLE
Forcing hidden hairline in navigationBars

### ISSUE THREAD

**Issue by pawelkata** [ViccAlexander/Chameleon#64]
The current version of Chameleon forces hidden hairline in all navigationBars throughout an app. While for some instances this is correct, I use Chameleon mainly for flat colors and missing hairline in navigation bars really messes up my UI. Is it necessary to force the hairline to be hidden?

Here's the code ```UINavigationController+Chameleon.m```:
```
- (void)chameleon_viewDidLoad {
    [self chameleon_viewDidLoad];
    
    UIView *heairlineImageView = [self findHairlineImageViewUnder:self.navigationBar];
    if (heairlineImageView) {
        heairlineImageView.hidden = NO; // I changed it from YES 
    }
}
```

Other than that this is an awesome framework! Thanks! :D

**Comment by ViccAlexander** [comment]
@pawelkata Thanks! I think you're correct in that it should be optional. I'll update Chameleon tomorrow!

**Comment by pawelkata** [comment]
@ViccAlexander Blazing fast response time! Thank you very much! I honestly can't imagine not using Chameleon in my apps :D

**Comment by bre7** [comment]
My bad. There needs to be a new bool to control this

**Comment by ViccAlexander** [comment]
@pawelkata No worries. I'm glad you're finding it useful!
@bre7 It should be an easy fix. Oh and there's also a minor spelling mistake. :grinning: I'll do it tomorrow (later today) and update the status here.

**Comment by bre7** [comment]
> 
@bre7 It should be an easy fix. Oh and there's also a minor spelling mistake. :grinning: I'll do it tomorrow (later today) and update the status here.

True 😅😅😓😓

**Comment by ViccAlexander** [comment]
Sorry it took an extra day. I just updated Chameleon to `2.0.3`. By default the hairline is no longer hidden. However, for those that do want to hide it, you can simple do the following inside a `UIViewController`:

``` objective-c 
[self.navigationController setHidesNavigationBarHairline:YES];

//or

self.navigationController.hidesNavigationBarHairline = YES;
```

Or if you rather do it from inside a `UINavigationController` you can do:

``` objective-c 
[self setHidesNavigationBarHairline:YES];

//or

self.setHidesNavigationBarHairline:YES;
```

Good luck @pawelkata!

**Comment by pawelkata** [comment]
Awesome! Thanks! :D
