### ISSUE TITLE
'Unrecognized selector' sent to class

### ISSUE THREAD

**Issue by fbara** [ViccAlexander/Chameleon#67]
I've been using Chameleon in my app for about 18 months and I haven't had a problem.  I changed my app to use cocoapods (along with other updates) so I had to update all the `#import` statements from `#import "Chameleon.h"` to `#import <ChameleonFramework/Chameleon.h>`.

I'm now receiving an error when I use either `ComplementaryFlatColor` or `ContrastColor`.  The error I receive is 
`+[UIColor colorWithComplementaryFlatColorOf:]: unrecognized selector sent to class 0x104909708
+[CATransaction synchronize] called within transaction
+[CATransaction synchronize] called within transaction
+[CATransaction synchronize] called within transaction
*** Terminating app due to uncaught exception
'NSInvalidArgumentException', reason: '+[UIColor colorWithComplementaryFlatColorOf:]: unrecognized selector sent to class 0x104909708'`

I have verified the Chameleon files imported properly because I can ⌘-click either macro and it takes me to the `ChameleonMacros.h` file and their #define statement.  I've confirmed that `Chameleon.h` imports the macro file.  I've set a breakpoint on the line `+ (UIColor *)colorWithComplementaryFlatColorOf:(UIColor *)color` as well as `+ (UIColor *)colorWithComplementaryFlatColorOf:(UIColor *)color withAlpha:(CGFloat)alpha` but the breakpoints are not hit.  

Here is my code and I'll explain the relevant parts below:
![screen shot 1](https://cloud.githubusercontent.com/assets/5705015/10345995/810eb736-6cf2-11e5-95aa-24f65224294b.png)

The `colorHome` variable is a UIColor.  The `self.homeTeamName.backgroundColor` is the background color of a UILabel.  I thought I might be sending an empty color to the function so I checked `colorHome` and verified it contained a color:
![screen shot](https://cloud.githubusercontent.com/assets/5705015/10346084/f245360a-6cf2-11e5-9f81-062dac09ae9f.png)

All of this exact same code worked prior to moving to cocoapods and for various reasons I don't/can't move back to the way the app used to be written.  Can you please provide some guidance on what I need to look for to resolve this issue?  Also, I'm not sure why I started to receive the `+[CATransaction synchronize] called within transaction` errors, either.  I haven't seen those errors until now so I think it's related.  Thanks.

**Comment by fbara** [comment]
After commenting out the code above, I started getting many more errors.  These are all on every use of Chameleon in my project.  It appears I'm getting the same `Unrecognized selector` error every time I use a color (such as `flatBlack`) or call any Chameleon function.

This is all Obj-C and Xcode 7.0.1.

**Comment by bre7** [comment]
Could you try downloading cloning Chameleon from the repo and delete the pod for now ? Same result ?

**Comment by ViccAlexander** [comment]
@fbara What Cocoapods version are you using? Also are you using this within an extension?

**Comment by fbara** [comment]
I'm using cocoapods v0.38.2.  I cloned the repo on a different project and it worked fine.  I then took another project that I used Chameleon (with cocoapods) and updated that to the latest Chameleon pod.  That worked fine, too.

It now looks like the problem is not with Chameleon but something in my code.  I'm going to close this issue.  Thanks @bre7 and @ViccAlexander for trying to help.

**Comment by fbara** [comment]
I closed this without leaving the correct comment.  It appears the problem is with my code.  I was able to clone the repo and use it in another project and it worked fine.  I also updated the Chameleon pod on a different project and that worked fine, too.  I'm going to close this issue.  Thanks @bre7 and @ViccAlexander for your help.

**Comment by ViccAlexander** [comment]
No prob. Hope you figure it out!

**Comment by fbara** [comment]
@ViccAlexander, thx.  While I have you here, I think it's weird that the error appears to be referencing your internal code because it's saying `'NSInvalidArgumentException', reason: '+[UIColor flatNavyBlueColor]: unrecognized selector sent to class`.   For reference, I removed the pod, cloned the repo, and added the Chameleon folder (which only contains the Chameleon.h file and Info.plist) to my project.  I can successfully import the file to my classes and I can ⌘-click the colors and functions to bring me to your source class.  I think it's all wired correctly and Xcode has access to all the files it needs.  The error references your class method, and it happens with every reference I have to anything Chameleon, and I don't receive any errors when I build the project.  I only get these errors when I try to run.  I'm really confused.
