### ISSUE TITLE
UIMenuViewController button style

### ISSUE THREAD

**Issue by skytoup** [ViccAlexander/Chameleon#72]
![png](http://7xjl2z.dl1.z0.glb.clouddn.com/1.png)
```objc
UIColor *c = [UIColor colorWithGradientStyle:UIGradientStyleRadial withFrame:CGRectMake(0, 0, 960, 960) andColors:@[[UIColor flatBlueColor], [UIColor flatPowderBlueColor]] ];
[Chameleon setGlobalThemeUsingPrimaryColor:c withSecondaryColor:c andContentStyle:UIContentStyleLight];
```
button is ugly

**Comment by bre7** [comment]
1. I'm not sure if gradients were meant to be used with GlobalTheme functions.
2. Theme functions set a UIButton's style using a bg color only (no rounded borders...So they'll look like solid rectangles/squares).

Also, what do you mean by ugly ? Are you reporting a bug or is the dark view behind it intended ? GlobalTheme functions are just a starting point, you should customize any specific view as you see fit (e.g: rounded corners, shadows, border width, etc.)

**Comment by skytoup** [comment]
using the [Chameleon setGlobalThemeUsingPrimaryColor:withSecondaryColor:andContentStyle:] function, which leads to the UIMenuViewController is not beautiful.
Because the UIMenuViewController button is a rounded corners, but the set up is a rectangles

**Comment by bre7** [comment]
I think it's intended. You can easily add rounded corners to every UIButton using UIButton.appearance()

**Comment by skytoup** [comment]
I mean, Chameleor set a theme, affecting UIMenuViewController button style, make it ugly

**Comment by ViccAlexander** [comment]
@skytoup Due to the way in which gradient colors are generated, gradient colors should **not** be expected to work with themes. The reason for this is due to frame sizes. Gradient colors are generated as an image, which is then used to color an element. The element's size needs to be known ahead of time for this to work. However because theming occurs prior to the creation of elements, unexpected results may occur. I'll look into finding a way for this to hopefully change, but I can't promise anything.

As for the `UIMenuViewController, I'll look into finding a way to support this.

**Comment by skytoup** [comment]
Actually I just want you to see if there are any way to change it nicely~~~

**Comment by ViccAlexander** [comment]
@skytoup  Sorry it's taken long for me to get to this. :disappointed: I've looked into it and unfortunately it looks like there's no way of correcting the look of the `UIMenuController` items without affecting the appearance of all `UIButtons`. Our best bet would be for Apple to allow `UIMenuController` to conform to the `UIAppearance` protocol. It seems to be more of an Apple limitation than anything.

Alternatively, here's your options:

1. Use a third party menu controller instead ([MenuPopOverView](https://github.com/camelcc/MenuPopOverView) looks good).

2. Comment out the following 2 lines in the `+ (void)customizeButtonWithPrimaryColor:(UIColor *)primaryColor withContentStyle:(UIContentStyle)contentStyle;` method inside `Chameleon_.m`:

``` objective-c
[[UIButton appearance] setTintColor:contentColor];
[[UIButton appearance] setBackgroundColor:primaryColor];
```

The only problem is that you'll have to handle the appearance of most `UIButton`s yourself. Good luck!

**Comment by skytoup** [comment]
Thank~

**Comment by ViccAlexander** [comment]
@skytoup No worries, good luck on your project!
