### ISSUE TITLE
SFSafariViewController looks weird

### ISSUE THREAD

**Issue by badgercl** [ViccAlexander/Chameleon#74]
Hi,

SFSafariViewController views presented in apps using Chameleon are using part of the color scheme, and they do not look ok.

For instance, to the demo app I added an IBAction to the example button with the code: 

```swift
@IBAction func openSafari(sender: AnyObject) {
     if #available(iOS 9.0, *) {
         let safariView = SFSafariViewController(URL: NSURL(string: "https://duckduckgo.com")!)
         self.presentViewController(safariView, animated: true, completion: nil)
     }
 }
```

When clicking the button the presented SFSafariViewController looks: 
![screen shot 2015-10-14 at 6 15 31 pm](https://cloud.githubusercontent.com/assets/4398862/10498173/f85f9556-72a8-11e5-949f-27e3c08a0e3a.png)

You can notice the URL bar and the *done* button have the background color, but the rest of the navbar and status bars have the standard grey.

Is there a way to have the SFSafariViewController fully themed or can I add an exception to leave SFSafariViewController with the default color schema?

Thanks!

**Comment by bre7** [comment]
There might be a way to theme it. I'll have a look next week or we'll need to think of a way to add exceptions (if there isn't one already) to solve this issue an #72 also.

**Comment by ViccAlexander** [comment]
This is definitely "fixable". There may be a way to exclude it from being themed, but it wouldn't be ideal. Instead, we should find a way to theme it as a regular view controller would be themed, with a few modifications so it doesn't look bad. @bre7 Let me look into this while I also look into #72.

**Comment by bre7** [comment]
Not sure if possible for the time being: http://stackoverflow.com/questions/33246813/how-to-change-the-background-color-of-a-sfsafariviewcontroller

**Comment by badgercl** [comment]
So, probably it would be nice to not apply any styles to SFSafariViewController at all :)

**Comment by bre7** [comment]
Yeah. Exceptions can't be added I think. @ViccAlexander kinda hacky but the only possible solution I thought would be to swizzle SFVC viewDidLoad and set the components' style back to default.

**Comment by ViccAlexander** [comment]
Looked into this and as @bre7 pointed out, there really isn't much that can be done until Apple fixes this themselves. Apple does however mention that if you'd like to customize the web content and controller, you're better off using `WKWebView` instead.

From [Apple Docs](https://developer.apple.com/library/prerelease/ios/documentation/SafariServices/Reference/SFSafariViewController_Ref/index.html):
> Use the `SFSafariViewController` class if your app lets users view websites from anywhere on the Internet. Use the `WKWebView` class if your app customizes, interacts with, or controls the display of web content.

@bre7 Swizzling could work, but I don't think it's absolutely necessary when other options exist (`WKWebView`). Hopefully in the next iOS release, we can get this fixed. If you'd like to give it a shot, feel free to do so though, and if it works, you can reopen this issue back up. :+1:

**Comment by badgercl** [comment]
Actually, you are missing something really important.

The goal of SFSafariViewController is to show **external** links without leaving the current application. This controller runs in a separated thread and uses all the Safari-managed credentials. For instance if you have logged at Facebook in the Safari App, when you open a FB link using SFSafariViewController from your application, instead is showing a FB-login screen, you'll see immediately the content since the SafariController uses the Safari App FB credentials.

It's true we can use UIWebView or WKWebView to show external links, but it makes the developer to create a ViewController, embed the WebView and handle the callbacks. Also the Safari-managed credentials are not available.

In addition, from iOS 9 Apple introduced [App Transport Security](https://developer.apple.com/library/prerelease/ios/releasenotes/General/WhatsNewIniOS/Articles/iOS9.html#//apple_ref/doc/uid/TP40016198-SW14) which tries to enforce high quality security by blocking insecure connections. 

That means any outgoing connections from an app, using NSURLConnection, NSURLSession or WebViews, have to meet the ATS requirements or they are going to be blocked. Since the feature we are trying to implement is an viewer for external links, we cannot control the security features of other servers. That means we'll need to create a wildcard exception for ATS making the app vulnerable to attacks. Probably Apple introduced the SFSafariViewController considering that issue.

While you can push an update on the issue found an ugly workaround for the styling issue by setting the Chameleon Theme to Safari colors and then immediately putting the app theme back:

``` Objective-C
[Chameleon setGlobalThemeUsingPrimaryColor:[UIColor whiteColor] withContentStyle:(UIContentStyle)UIContentStyleContrast];
SFSafariViewController *safari = [[SFSafariViewController alloc] initWithURL:[NSURL URLWithString:url]];
[self.navigationController presentViewController:safari animated:YES completion:NULL];
[Chameleon setGlobalThemeUsingPrimaryColor:[UIColor mainColor] withContentStyle:(UIContentStyle)UIContentStyleContrast]
```

**Comment by Gargam** [comment]
Hello,

This also affect video player controls (triggered from youtube iframe in WKWebView in my case, but I think it will do the same for any other player that show up).

**Comment by shusain93** [comment]
This is the code I got to work perfectly with `SFSafariViewController` however I can't seem to get the buttons to be the right bluish color but it works.

 `Chameleon.setGlobalThemeUsingPrimaryColor(nil, withSecondaryColor: nil, andContentStyle: UIContentStyle.dark)`

**Comment by shusain93** [comment]
Three days later I'd like to make an update that this did not work perfectly and seems to have completely broken the performance of `SFSafariViewController`. Can we get this issue reopened? It seems that iOS 10 has somehow made this worse. You get the lovely duo of screwy UI and buggy performance.

**Comment by tehjord** [comment]
It looks like any solution might be too hackish, but ++ for a fix for to this.

Using a WKWebView is definitely not a proper alternative to SFSafariViewController.
