### ISSUE TITLE
CGContextDrawImage leaking?

### ISSUE THREAD

**Issue by KiranPanesar** [ViccAlexander/Chameleon#75]
Love the framework, but we're running into an issue where it looks like Chameleon's colour-generation is leaking. 

We're using the `+arrayOfColorsFromImage:withFlatScheme:(BOOL)isFlatScheme` to generate complementary colours around our main image. Calling this even around 7 times resulting in our persistent memory usage doubling.

When I dig into how the method works internally, I'm noticing that removing the call to `CGContextDrawImage` from `UIColor+ChameleonPrivate.m:50`, the high memory usage ceases. 

Is anyone able to replicate this?

**Comment by ViccAlexander** [comment]
@KiranPanesar Let me look into this and get back to you. Thanks for pointing this out!

**Comment by ViccAlexander** [comment]
@KiranPanesar Thanks for the kind words. Hmm... I'm glad you've figured out a solution. Can you see if making the changes suggested in pull request #76 solve it (without removing `CGContextDrawImage`) though.

**Comment by KiranPanesar** [comment]
Hi @ViccAlexander. Removing the cast for `calloc` won't fix the issue. We actually found that we can remove the memory leak if we disable decompression of our images by our caching library (`SDWebImage`). If you pass in a decompressed image into `CGContextDrawImage`, it'll leak memory. But if you pass in a _compressed_ image, `CGContextDrawImage` will be fine.

**Comment by bre7** [comment]
Have you tried Chameleon without SDWebImage and if needed, a networking lib only ? There's an open issue regarding memory leaks in SDWebImage (538).
