### ISSUE TITLE
ColorsFromImage returns white only

### ISSUE THREAD

**Issue by Sittenstrolch** [ViccAlexander/Chameleon#89]
Hello,

the above function does not work on a given image, neither with both true and false for the parameter isFlatScheme. The AverageColor function works fine on the same image.

What could lead to this problem?

**Comment by ViccAlexander** [comment]
@Sittenstrolch I just tried it on the following image and it worked fine. Can you post your code so I can see what you're doing?

![screen shot 2015-11-25 at 10 36 42 pm](https://cloud.githubusercontent.com/assets/1724674/11416692/1631a0b4-93c5-11e5-8e27-6d0a530495cf.png)

I added my code below, including the image I used.

``` objective-c
self.imageView.image = [UIImage imageNamed:@"lambo.jpg"];
NSArray *colors = [NSArray arrayOfColorsFromImage:self.imageView.image withFlatScheme:NO];
self.view1.backgroundColor = colors[0];
self.view2.backgroundColor = colors[1];
self.view3.backgroundColor = colors[2];
self.view4.backgroundColor = colors[3];
self.view5.backgroundColor = colors[4];
```

![lambo](https://cloud.githubusercontent.com/assets/1724674/11416731/554a355e-93c5-11e5-9f0b-07bb5f218740.jpg)

**Comment by Sittenstrolch** [comment]
@ViccAlexander I think the main difference is that im using swift2.

I'm fetching the images from a url and pass them into a callback function. The images are displayed correctly and the average Color also works fine. But the ColorsFromImage returns white only.

This is how I integrated your Pod into my Project:

pod 'ChameleonFramework/Swift'

My Code:
```
{ 
image in
  let palette = ColorsFromImage(image, true)
  print(palette)
  let avgColor =  AverageColorFromImage(image)
  print(avgColor)
}
```

And the output is:
```
[
  UIDeviceWhiteColorSpace 1 1, 
  UIDeviceWhiteColorSpace 1 1, 
  UIDeviceWhiteColorSpace 1 1, 
  UIDeviceWhiteColorSpace 1 1, 
  UIDeviceWhiteColorSpace 1 1
]
UIDeviceRGBColorSpace 0.0431373 0.247059 0.188235 1
```

And here is the image, the output was created from:
![385](https://cloud.githubusercontent.com/assets/5831420/11426750/78e79aee-945e-11e5-8d79-b44b1a54f5a6.png)

**Comment by bre7** [comment]
@Sittenstrolch Could you try the *same* example in both objc and swift ? This shouldn't be the issue since swift functions are only shorthands

**Comment by Sittenstrolch** [comment]
I honestly don't really know how to use objective-c within my swift project. Have you tried it with swift?

**Comment by bre7** [comment]
My bad :hand: Fixed it... Thanks for the report @Sittenstrolch, try using `:head` in CocoaPods/carthage to

@ViccAlexander bump version with this fix when you can.

**Comment by ViccAlexander** [comment]
@bre7 Gotcha. @Sittenstrolch Chameleon 2.0.6 is now available. Updating should fix your issue. :+1:

**Comment by Sittenstrolch** [comment]
Great! It works ;)
