### ISSUE TITLE
Add font color change 

### ISSUE THREAD

**Issue by vinnyoodles** [ViccAlexander/Chameleon#92]
```swift
view.backgroundColor = RandomFlatColor()
```

Added this for fun and found that some of the darker colors left the text as black and made it harder to read

But besides that, I found this pod to super useful and very easy to install.

**Comment by vinnyoodles** [comment]
Just found the `Theme Methods` which looks like it does change the font color to fit better, but the README doesn't show the swift commands

**Comment by bre7** [comment]
Hi vin, there's no api for that in Chameleon, even in objc. It changes the tint color of some components.
