### ISSUE TITLE
Different colors between the palette and the library

### ISSUE THREAD

**Issue by juancazalla** [ViccAlexander/Chameleon#97]
I'm using the color palette in Xcode and the colors are different from those set by code. For example flatRedColor

**Comment by bre7** [comment]
When applying to color to the navBar or any view ? Is `translucent` enabled ?

**Comment by juancazalla** [comment]
In any view. With two different views, I set the background of a view with the palette and the other by code and they are different

**Comment by bre7** [comment]
Would you mind doing the following:
1. Upload a screenshot of both views
2. Paste the console output of `view.backgroundColor` for each view

The only thing I can think of is that the pallete might be outdated (which I highly doubt it)... cc @ViccAlexander

**Comment by ViccAlexander** [comment]
@juancazalla I ran a few tests and weird things are def happening. I built a quick project to show the differences between setting a view's `backgroundColor` programmatically, and setting it via the palette. Here's the results:

![simulator screen shot jan 6 2016 3 51 19 pm](https://cloud.githubusercontent.com/assets/1724674/12158268/5c21bf4e-b48d-11e5-9008-f9f9133756ab.png)

You are correct, they are different. The correct color should be the one set programmatically (top one). Here's the things I asked myself:

**1. Is the color generated on the screen for the programmatically colored background the same as the code or is it altered somewhere in the process before being displayed?** Answer: *It's the same.*

I checked the HSB values of the view after it appears and these are the values:
> Hue: 145 Saturation: 77% Brightness: 80%

This matches the FlatGreenColor method:
``` objective-c
+ (UIColor *)flatGreenColor {
    return hsb(145, 77, 80);
}
```

**2. Could it be a trick on the eyes?** Answer: *Nope they are definitely different. The values don't match between the palette and the method values.*

The HSB values for the storyboard palette both before and after are:
> Hue: 129 Saturation: 70% Brightness: 78%  

which is definitely different than the previous values. 

**3. Could I have made a mistake or is storyboard doing something funny?** Answer: *Both.*
I don't have the files for the palette on me so I cannot say with 100% certainty if I entered the correct or incorrect values when building the palette, however I can say storyboard is doing something funny. If you go into storyboard, and set the `FlatGreen`'s HSB values to
 > Hue: 145 Saturation: 77% Brightness: 80%   

you'll find you get the correct color. However, if you switch to RGB and back, Storyboard changes the HSB values a bit. This could mean that even if I entered the correct values initially, storyboard is definitely altering them. 

Now it doesn't alter them drastically like the differences we're seeing originally, so I might have an idea of what could be going wrong. I'm not 100% sure, but it could be that when I made the palette I was using RGB, when I should have used HSB. I'll look into updating it this weekend to make sure everything is correct.

In the meantime, if you really need the storyboard palette support, check out @sephiroth87's Xcode plugin [**Crayons**](https://github.com/Sephiroth87/Crayons). He included Chameleon Colors into it by default (Not sure if it has the same problem though).

**Comment by Sephiroth87** [comment]
There's definitely something funky happening in Xcode itself, just selecting any color in the picker and changing from RGB to HSB sliders, the color will keep changing values and get progressively darker...

**Comment by bre7** [comment]
Could you guys test the new palette I uploaded ? Available for download in #107 (Converted all colors to strings, json and finally CLR)

**Comment by ViccAlexander** [comment]
Hey @bre7 Thanks for holding down the fort. I've been crazy busy lately, but I'm back now. Let me test it and get back to you.

**Comment by bre7** [comment]
np :wink:

**Comment by A1exandre** [comment]
Hi guys, 

I still have the same issue with colors that look different depending on when I set them from Xcode's palette and when I set them programmatically.

Has anyone figured this out?

**Comment by ViccAlexander** [comment]
@bre7  It's been a while, but how would we incorporate this automatically into the latest Chameleon update.

**Comment by bre7** [comment]
The issue is the SB plugin so the clrs *supposedly* fixed the palette differences
