### ISSUE TITLE
TableViewCell accessory color when using theme

### ISSUE THREAD

**Issue by bharatkrishna** [ViccAlexander/Chameleon#99]
I am setting a global theme color in AppDelegate.swift:

> Chameleon.setGlobalThemeUsingPrimaryColor(FlatSkyBlue(), withContentStyle: UIContentStyle.Contrast)

This makes all buttons and accessory in TablwViewCells to have blue background which makes it look odd: 

![screen shot 2016-01-19 at 10 04 43 pm](https://cloud.githubusercontent.com/assets/240429/12441191/59cf1748-bef9-11e5-8d45-19bec6387e6a.png)

Can TablwViewCells accessories be excluded from the theme colors? I intend to keep the color of TableViewCell itself as white. So the accessory should have white background.

**Comment by AnthonyOSX** [comment]
Duplicate of #98

**Comment by bharatkrishna** [comment]
Closing as duplicate of https://github.com/ViccAlexander/Chameleon/issues/98
